### ISSUE TITLE
Postman Collections are empty only japan version is there

### ISSUE THREAD

**Issue by KenZync** [box/box-postman#30]
## Description of the issue
https://www.postman.com/boxdev/workspace/box-s-public-workspace/collection/8119550-b5ea2aeb-c82a-425d-baff-ed5dfd1d7659
When I fork from https://developer.box.com/guides/tooling/postman/quick-start/load-postman-collection/
It fork empty because source is empty

## Current content
Empty Fork

## Expected content
Excepcted collection of fork

**Comment by barduinor** [comment]
Collections re-deployed
